title: "Sabit Agić – Lutkar i Kompozitor"
description: "Dobrodošli na moj portfolio! Ovdje možete pronaći moje pjesme, lutkarske predstave i muzičke projekte."
baseurl: ""
url: "https://sabitagic.github.io"

theme: agency-jekyll-theme

people:
  - name: Sabit Agić
    pic: /img/about/sabit.webp
    position: Učitelj
    social:
      - title: facebook
        url: https://www.facebook.com/lutkarstvo.sabit.agic/?locale=hr_HR
      - title: youtube
        url: https://www.youtube.com/channel/UCxpaTNTPVRPNZ20gqmr-VvQ

press:
  - title: "Lutke kao alat za očuvanje zdravlja djece tokom nastave"
    url: "https://www.ucitelj21.com/2016/11/i-ucitelj-i-lutkar-sabit-agic.html"
    description: "Članak govori o zanimljivom pristupu nastavi u kojem se lutke koriste kako bi djeca aktivno učestvovala i učila kroz igru. Kroz predstave poput 'Lutke nam pričaju', djeca se na zabavan način upoznaju s važnim temama, poput pravilnog sjedenja, dok nastava postaje interaktivna i motivirajuća. Ovaj način rada izaziva pozitivne reakcije i kod djece i roditelja."
  - title: "Kroz igru s lutkama do motivacije za učenje"
    url: "https://www.mreza-mira.net/vijesti/obrazovanje/ucitelj-lutkar/"
    description: "Sabit Agić, učitelj i lutkar, koristi lutke kako bi nastavu učinio zabavnijom i interaktivnijom. Kroz igru, djeca ne samo da uče važne životne lekcije, već se i opuštaju, bez straha od greške. Agić stvara atmosferu u kojoj djeca mogu biti kreativna i slobodna, ističući kako igra igra ključnu ulogu u učenju i socijalizaciji. Kroz humor i igru, on podstiče djecu na razmišljanje i aktivno učešće u nastavi."
  - title: "Upoznajte dr. Hećima i gospodina Spužvu: Učitelj Sabit Agić u radu s učenicima koristi lutke"
    url: "https://www.klix.ba/vijesti/upoznajte-dr-hecima-i-gospodina-spuzvu-ucitelj-sabit-agic-u-radu-s-ucenicima-koristi-lutke/150401062#google_vignette"
    description: "Učitelj Sabit Agić koristi lutke kao alat u nastavi kako bi djeci učinio obrazovanje zabavnijim i učinkovitijim. Kroz likove poput dr. Hećima, lutke pomažu u održavanju pažnje učenika i podučavaju ih važnim temama, poput pravilnog držanja tijela i zdravlja. Agić koristi lutke u svim predmetima, a istovremeno potiče učenike da razvijaju vlastite ideje i kreativnost."

social:
  - title: facebook
    url: https://www.facebook.com/lutkarstvo.sabit.agic/?locale=hr_HR
  - title: youtube
    url: https://www.youtube.com/channel/UCxpaTNTPVRPNZ20gqmr-VvQ

address:
  - line: 71000 Sarajevo
  - line: Bosna i Hercegovina

markdown: kramdown
permalink: pretty
